### ISSUE TITLE
Production Kubernetes

### ISSUE THREAD

**Issue by DominicRoyStang** [BlockedTODO/BlockedTODO#105]
Acceptance Criteria:

**Part 1**
- [x] I can access the frontend service at app.blockedtodo.com
- [x] I can access the backend service at backend.blockedtodo.com

**Part 2**
- [x] The services can communicate with eachother

**Part 3**
- [x] There is a production database
- [x] the backend service can communicate with the database service

**Part 4**
- [x] The services communicate via HTTPS

**Part 5**
- [x] On every push to master, the production k80s cluster is updated with the newest images
