### ISSUE TITLE
Keep track of GitHub installation IDs

### ISSUE THREAD

**Issue by DominicRoyStang** [BlockedTODO/BlockedTODO#183]
This issue originates from this comment https://github.com/BlockedTODO/BlockedTODO/issues/176#issuecomment-659076343

Checklist:

**Part 1**
- [x] Add installation IDs as an optional field on repository in a migration
- [x] Update existing code to support installation IDs
- [x] Update GitHub webhook installation events to add installation IDs
- [x] Add unit tests for installation id on model
- [x] Write job that gets installation ids and adds them to existing records
- [x] Merge code
- [x] Run job in production

**Part 2**
- [x] Add migration making installation IDs mandatory
- [x] Merge code
- [x] Verify successful migration in prod
